version: '3'

services:
  app:
    image: node:12.13
    command: sh -c "npm i && npm run serve"
    restart: always
    volumes:
      - './:/app'
    working_dir: /app
    ports:
      - "8016:8080"
